## Import Libraries

In [ ]:
import numpy as np
import pandas as pd
import os
import re

pd.options.display.max_columns = None
pd.options.display.max_rows = 200

### Import Data

In [ ]:
data_csv = "/content/fifa21_raw_data.csv"
data = pd.read_csv(data_csv)

# Cleaning & Processing

In [ ]:
data.head()

,Name,Nationality,Positions,Age,Team,Contract,Overal,Potential,Height,Weight,foot,Best Overall,Blance,Growth,Value,Wage,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,Dribbling,Curve,FK Accuracy,Long Passing,Ball Control,Movement,Acceleration,Sprint Speed,Agility,Reactions,Balance,Power,Shot Power,Jumping,Stamina,Strength,Long Shots,Mentality,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Defending,Marking,Standing Tackle,Sliding Tackle,Goalkeeping,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes,Total Stats,Base Stats,W/F,SM,A/W,D/W,Reputation,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,L. Messi,Argentina,RW ST CF,33,FC Barcelona,2004 - 2021,93,93,170,72,Left,93,RW,0,67500000.0,560000.0,429,85,95,70,91,88,470,96,93,94,91,96,451,91,80,91,94,95,389,86,68,72,69,94,347,44,40,93,95,75,96,91,32,35,24,54,6,11,15,14,8,2231,466,4,4,Medium,Low,5,85,92,91,95,38,65,372.0
1,Cristiano Ronaldo,Portugal,ST LW,35,Juventus,2018 - 2022,92,92,188,83,Right,92,ST,0,46000000.0,220000.0,437,84,95,90,82,86,414,88,81,76,77,92,431,87,91,87,95,71,444,94,95,84,78,93,353,63,29,95,82,84,95,84,28,32,24,58,7,11,15,14,11,2221,464,4,5,High,Low,5,89,93,81,89,35,77,344.0
2,J. Oblak,Slovenia,GK,27,Atl√©tico Madrid,2014 - 2023,91,93,188,87,Right,91,GK,2,75000000.0,125000.0,95,13,11,15,43,13,109,12,13,14,40,30,307,43,60,67,88,49,268,59,78,41,78,12,140,34,19,11,65,11,68,57,27,12,18,437,87,92,78,90,90,1413,489,3,1,Medium,Medium,3,87,92,78,90,52,90,86.0
3,K. De Bruyne,Belgium,CAM CM,29,Manchester City,2015 - 2023,91,91,180,70,Right,91,CAM,0,87000000.0,370000.0,407,94,82,55,94,82,441,88,85,83,93,92,398,77,76,78,91,76,408,91,63,89,74,91,408,76,66,88,94,84,91,186,68,65,53,56,15,13,5,10,13,2304,485,5,4,High,High,4,76,86,93,88,64,78,163.0
4,Neymar Jr,Brazil,LW CAM,28,Paris Saint-Germain,2017 - 2022,91,91,175,68,Right,91,LW,0,90000000.0,270000.0,408,85,87,62,87,87,448,95,88,89,81,95,453,94,89,96,91,83,357,80,62,81,50,84,356,51,36,87,90,92,93,94,35,30,29,59,9,9,15,15,11,2175,451,5,5,High,Medium,5,91,85,86,94,36,59,273.0

In [ ]:
data.describe(include=object)

,photoUrl,LongName,playerUrl,Nationality,Positions,Name,Team & Contract,Height,Weight,foot,BP,Joined,Loan Date End,Value,Wage,Release Clause,W/F,SM,A/W,D/W,IR,Hits
count,18979,18979,18979,18979,18979,18979,18979,18979,18979,18979,18979,18979,1013,18979,18979,18979,18979,18979,18979,18979,18979,18979
unique,18978,18851,18978,164,640,17919,9023,21,56,2,15,1869,24,214,141,1216,5,5,3,3,5,408
top,https://cdn.sofifa.com/players/251/698/21_60.png,Liam Kelly,http://sofifa.com/player/251698/kevin-berlaso/...,England,CB,J. Rodr√≠guez,\n India\nFree\n\n,"6'0""",154lbs,Right,CB,"Jul 1, 2019","Jun 30, 2021",‚Ç¨1.1M,‚Ç¨2K,‚Ç¨0,3 ‚òÖ,2‚òÖ,Medium,Medium,1 ‚òÖ,\n1
freq,2,3,2,1704,2441,13,29,2859,1496,14445,3685,1344,770,467,2997,1262,11695,9142,12700,13956,17628,3216

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 77 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   photoUrl          18979 non-null  object
 1   LongName          18979 non-null  object
 2   playerUrl         18979 non-null  object
 3   Nationality       18979 non-null  object
 4   Positions         18979 non-null  object
 5   Name              18979 non-null  object
 6   Age               18979 non-null  int64
 7   ‚ÜìOVA              18979 non-null  int64
 8   POT               18979 non-null  int64
 9   Team & Contract   18979 non-null  object
 10  ID                18979 non-null  int64
 11  Height            18979 non-null  object
 12  Weight            18979 non-null  object
 13  foot              18979 non-null  object
 14  BOV               18979 non-null  int64
 15  BP                18979 non-null  object
 16  Growth            18979 non-null  int64
 17  Joined            18979 non-null  object
 18  Loan Date End     1013 non-null   object
 19  Value             18979 non-null  object
 20  Wage              18979 non-null  object
 21  Release Clause    18979 non-null  object
 22  Attacking         18979 non-null  int64
 23  Crossing          18979 non-null  int64
 24  Finishing         18979 non-null  int64
 25  Heading Accuracy  18979 non-null  int64
 26  Short Passing     18979 non-null  int64
 27  Volleys           18979 non-null  int64
 28  Skill             18979 non-null  int64
 29  Dribbling         18979 non-null  int64
 30  Curve             18979 non-null  int64
 31  FK Accuracy       18979 non-null  int64
 32  Long Passing      18979 non-null  int64
 33  Ball Control      18979 non-null  int64
 34  Movement          18979 non-null  int64
 35  Acceleration      18979 non-null  int64
 36  Sprint Speed      18979 non-null  int64
 37  Agility           18979 non-null  int64
 38  Reactions         18979 non-null  int64
 39  Balance           18979 non-null  int64
 40  Power             18979 non-null  int64
 41  Shot Power        18979 non-null  int64
 42  Jumping           18979 non-null  int64
 43  Stamina           18979 non-null  int64
 44  Strength          18979 non-null  int64
 45  Long Shots        18979 non-null  int64
 46  Mentality         18979 non-null  int64
 47  Aggression        18979 non-null  int64
 48  Interceptions     18979 non-null  int64
 49  Positioning       18979 non-null  int64
 50  Vision            18979 non-null  int64
 51  Penalties         18979 non-null  int64
 52  Composure         18979 non-null  int64
 53  Defending         18979 non-null  int64
 54  Marking           18979 non-null  int64
 55  Standing Tackle   18979 non-null  int64
 56  Sliding Tackle    18979 non-null  int64
 57  Goalkeeping       18979 non-null  int64
 58  GK Diving         18979 non-null  int64
 59  GK Handling       18979 non-null  int64
 60  GK Kicking        18979 non-null  int64
 61  GK Positioning    18979 non-null  int64
 62  GK Reflexes       18979 non-null  int64
 63  Total Stats       18979 non-null  int64
 64  Base Stats        18979 non-null  int64
 65  W/F               18979 non-null  object
 66  SM                18979 non-null  object
 67  A/W               18979 non-null  object
 68  D/W               18979 non-null  object
 69  IR                18979 non-null  object
 70  PAC               18979 non-null  int64
 71  SHO               18979 non-null  int64
 72  PAS               18979 non-null  int64
 73  DRI               18979 non-null  int64
 74  DEF               18979 non-null  int64
 75  PHY               18979 non-null  int64
 76  Hits              18979 non-null  object
dtypes: int64(55), object(22)
memory usage: 11.1+ MB

In [ ]:
data.shape

(18979, 77)

### Convert Datatime for Joined column

In [ ]:
data.Joined.value_counts()

Jul 1, 2019     1344
Jul 1, 2018      865
Jan 1, 2019      682
Jul 1, 2017      520
Jul 1, 2020      435
                ...
May 17, 2018       1
Feb 25, 2015       1
Jun 1, 2005        1
Sep 10, 2016       1
Feb 28, 2015       1
Name: Joined, Length: 1869, dtype: int64

In [ ]:
from numpy.core.fromnumeric import size
month_dict = {'Jan':1, 'Feb':2, 'Mar':3, 'Apr':4, 'May':5, 'Jun':6, 'Jul':7, 'Aug':8, 'Sep':9, 'Oct':10, 'Nov':11, 'Dec':12}

def convertDay(date : str):
    month, day, year = re.findall(r'\w+', date)
    month = month_dict.get(month)
    if day != None and len(day) < 2 : day = f"0{day}"
    if month != None and month/10 < 1: month = f"0{month}"
    return f"{year}-{month}-{day}"

data.Joined = data.Joined.apply(convertDay)

In [ ]:
data.Joined.value_counts()

2019-07-01    1344
2018-07-01     865
2019-01-01     682
2017-07-01     520
2020-07-01     435
              ...
2018-05-17       1
2015-02-25       1
2005-06-01       1
2016-09-10       1
2015-02-28       1
Name: Joined, Length: 1869, dtype: int64

In [ ]:
# Convert Joined to Datatime
data['Joined'] = pd.to_datetime(data['Joined'], format='%Y-%m-%d')

In [ ]:
print(data['Joined'].dtype)

datetime64[ns]

### Convert Height from feet-inch to centimeter

In [ ]:
data['Height'].value_counts()

6'0"     2859
5'10"    2654
5'9"     2304
5'11"    2188
6'2"     2108
6'1"     2001
5'8"     1069
6'3"     1049
5'7"      953
6'4"      797
5'6"      332
6'5"      280
5'5"      188
6'6"      116
5'4"       33
6'7"       20
5'3"       15
6'8"        6
5'2"        4
5'1"        2
6'9"        1
Name: Height, dtype: int64

In [ ]:
def convertHeight(height: str):
  if ("\'") not in height: return height
  feet, inch = pd.to_numeric(re.findall(r'\d+', string = height))
  return round(feet*30.48 + inch*2.54)
data['Height'] = data['Height'].apply(convertHeight)

In [ ]:
data['Height']

0        170
1        188
2        188
3        180
4        175
        ...
18974    178
18975    170
18976    178
18977    175
18978    175
Name: Height, Length: 18979, dtype: int64

### Converting Weight from Pound to Kg

In [ ]:
data['Weight'].value_counts()

154lbs    1496
165lbs    1458
176lbs    1109
159lbs    1024
172lbs     995
163lbs     957
161lbs     956
170lbs     893
168lbs     880
150lbs     795
174lbs     684
157lbs     648
181lbs     622
152lbs     566
143lbs     535
179lbs     523
183lbs     515
148lbs     508
185lbs     444
187lbs     423
146lbs     401
141lbs     341
190lbs     285
194lbs     266
139lbs     239
192lbs     224
137lbs     181
198lbs     156
132lbs     153
196lbs     128
134lbs      96
201lbs      87
203lbs      68
205lbs      52
128lbs      44
130lbs      41
207lbs      34
209lbs      30
126lbs      19
121lbs      17
212lbs      15
216lbs      13
123lbs      12
214lbs       9
220lbs       8
119lbs       5
227lbs       4
225lbs       4
223lbs       4
218lbs       3
229lbs       3
115lbs       2
236lbs       1
243lbs       1
117lbs       1
110lbs       1
Name: Weight, dtype: int64

In [ ]:
def convertWeight(weight: str):
  if 'lbs' not in weight: return weight
  lbs = pd.to_numeric(re.findall(pattern = '\d+', string = weight))[0]
  return round(lbs*0.453592)

data.Weight = data.Weight.apply(convertWeight)

In [ ]:
data.Weight

0        72
1        83
2        87
3        70
4        68
         ..
18974    70
18975    58
18976    66
18977    65
18978    68
Name: Weight, Length: 18979, dtype: int64

In [ ]:
data.head()

,photoUrl,LongName,playerUrl,Nationality,Positions,Name,Age,‚ÜìOVA,POT,Team & Contract,ID,Height,Weight,foot,BOV,BP,Growth,Joined,Loan Date End,Value,Wage,Release Clause,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,Dribbling,Curve,FK Accuracy,Long Passing,Ball Control,Movement,Acceleration,Sprint Speed,Agility,Reactions,Balance,Power,Shot Power,Jumping,Stamina,Strength,Long Shots,Mentality,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Defending,Marking,Standing Tackle,Sliding Tackle,Goalkeeping,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes,Total Stats,Base Stats,W/F,SM,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,https://cdn.sofifa.com/players/158/023/21_60.png,Lionel Messi,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,RW ST CF,L. Messi,33,93,93,\n\n\n\nFC Barcelona\n2004 ~ 2021\n\n,158023,170,72,Left,93,RW,0,2004-07-01,NaN,‚Ç¨67.5M,‚Ç¨560K,‚Ç¨138.4M,429,85,95,70,91,88,470,96,93,94,91,96,451,91,80,91,94,95,389,86,68,72,69,94,347,44,40,93,95,75,96,91,32,35,24,54,6,11,15,14,8,2231,466,4 ‚òÖ,4‚òÖ,Medium,Low,5 ‚òÖ,85,92,91,95,38,65,\n372
1,https://cdn.sofifa.com/players/020/801/21_60.png,C. Ronaldo dos Santos Aveiro,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,ST LW,Cristiano Ronaldo,35,92,92,\n\n\n\nJuventus\n2018 ~ 2022\n\n,20801,188,83,Right,92,ST,0,2018-07-10,NaN,‚Ç¨46M,‚Ç¨220K,‚Ç¨75.9M,437,84,95,90,82,86,414,88,81,76,77,92,431,87,91,87,95,71,444,94,95,84,78,93,353,63,29,95,82,84,95,84,28,32,24,58,7,11,15,14,11,2221,464,4 ‚òÖ,5‚òÖ,High,Low,5 ‚òÖ,89,93,81,89,35,77,\n344
2,https://cdn.sofifa.com/players/200/389/21_60.png,Jan Oblak,http://sofifa.com/player/200389/jan-oblak/210005/,Slovenia,GK,J. Oblak,27,91,93,\n\n\n\nAtl√©tico Madrid\n2014 ~ 2023\n\n,200389,188,87,Right,91,GK,2,2014-07-16,NaN,‚Ç¨75M,‚Ç¨125K,‚Ç¨159.4M,95,13,11,15,43,13,109,12,13,14,40,30,307,43,60,67,88,49,268,59,78,41,78,12,140,34,19,11,65,11,68,57,27,12,18,437,87,92,78,90,90,1413,489,3 ‚òÖ,1‚òÖ,Medium,Medium,3 ‚òÖ,87,92,78,90,52,90,\n86
3,https://cdn.sofifa.com/players/192/985/21_60.png,Kevin De Bruyne,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,CAM CM,K. De Bruyne,29,91,91,\n\n\n\nManchester City\n2015 ~ 2023\n\n,192985,180,70,Right,91,CAM,0,2015-08-30,NaN,‚Ç¨87M,‚Ç¨370K,‚Ç¨161M,407,94,82,55,94,82,441,88,85,83,93,92,398,77,76,78,91,76,408,91,63,89,74,91,408,76,66,88,94,84,91,186,68,65,53,56,15,13,5,10,13,2304,485,5 ‚òÖ,4‚òÖ,High,High,4 ‚òÖ,76,86,93,88,64,78,\n163
4,https://cdn.sofifa.com/players/190/871/21_60.png,Neymar da Silva Santos Jr.,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,LW CAM,Neymar Jr,28,91,91,\n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n,190871,175,68,Right,91,LW,0,2017-08-03,NaN,‚Ç¨90M,‚Ç¨270K,‚Ç¨166.5M,408,85,87,62,87,87,448,95,88,89,81,95,453,94,89,96,91,83,357,80,62,81,50,84,356,51,36,87,90,92,93,94,35,30,29,59,9,9,15,15,11,2175,451,5 ‚òÖ,5‚òÖ,High,Medium,5 ‚òÖ,91,85,86,94,36,59,\n273

In [ ]:
def split_team_contract(col=None):
  col = col.str.replace(r'^[\n]{4}','')     # x√≥a 4 k√≠ t·ª± '\n' ·ªü ƒë·∫ßu
  col = col.str.replace(r'[\n]{2}','')      # x√≥a 2 k√≠ t·ª± '\n' ·ªü cu·ªëi
  data[['Team','Contract']] = col.str.split('\n',1,expand=True)     # chia chu·ªói ·ªü v·ªã tr√≠ k√≠ t·ª± '\n'
  return col
data['Team & Contract'] = split_team_contract(data['Team & Contract'])

#drop column Team & Contract
data = data.drop(columns=['Team & Contract'])

<ipython-input-69-aec41679565b>:2: FutureWarning: The default value of regex will change from True to False in a future version.
  col = col.str.replace(r'^[\n]{4}','')     # x√≥a 4 k√≠ t·ª± '\n' ·ªü ƒë·∫ßu
<ipython-input-69-aec41679565b>:3: FutureWarning: The default value of regex will change from True to False in a future version.
  col = col.str.replace(r'[\n]{2}','')      # x√≥a 2 k√≠ t·ª± '\n' ·ªü cu·ªëi
<ipython-input-69-aec41679565b>:4: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  data[['Team','Contract']] = col.str.split('\n',1,expand=True)     # chia chu·ªói ·ªü v·ªã tr√≠ k√≠ t·ª± '\n'

In [ ]:
# Replace '~' to '-'
data['Contract'] = data['Contract'].str.replace('~', '-')

### Process Value, Wage and Rease Clause columns

In [ ]:
def clean_column(col):
  col = col.lstrip('‚Ç¨')
  end_char = col[-1]  #get the end character
  if end_char == 'M':
    return float(col[:-1]) * 1e6
  elif end_char == 'K':
    return float(col[:-1]) * 1e3
  else:
    return float(col)

In [ ]:
# excu clean_column function

data['Value'] = data['Value'].apply(clean_column)

data['Wage'] = data['Wage'].apply(clean_column)

data['Release Clause'] = data['Release Clause'].apply(clean_column)

### Process W/F, SM and IR columns

In [ ]:
# Remove '‚òÖ'
def remove_star(col):
  col = col.rstrip('‚òÖ')
  return int(col)

In [ ]:
# exc remove_star function
data['W/F'] = data['W/F'].apply(remove_star)

data['SM'] = data['SM'].apply(remove_star)

data['IR'] = data['IR'].apply(remove_star)

### Process Hits column

In [ ]:
def convert_value(col):
  if isinstance(col, str):
    col = col.lstrip('\n')
    if col.endswith('K'):
      return float(col[:-1]) * 1e3
    else:
      return float(col)
  else:
    return float(col)

In [ ]:
# exc convert_value function

data['Hits'] = data['Hits'].apply(convert_value)

### Process Loan Date End

In [ ]:
data['Loan Date End']= pd.to_datetime(data['Loan Date End'])

### Reorder the columns and drop (photoUrl, playerUrl, ID, Joined, Loan Date End) columns

In [ ]:
data = data[['Name','Nationality','Positions','Age','Team','Contract','‚ÜìOVA', 'POT','Height','Weight','foot','BOV','BP','Growth','Value','Wage','Attacking','Crossing','Finishing','Heading Accuracy','Short Passing',
             'Volleys','Skill','Dribbling', 'Curve','FK Accuracy','Long Passing', 'Ball Control','Movement','Acceleration','Sprint Speed','Agility','Reactions','Balance','Power','Shot Power','Jumping',	'Stamina',	'Strength',
             'Long Shots','Mentality',	'Aggression','Interceptions',	'Positioning',	'Vision','Penalties',	'Composure',	'Defending',	'Marking','Standing Tackle','Sliding Tackle','Goalkeeping','GK Diving',	'GK Handling',
             'GK Kicking',	'GK Positioning',	'GK Reflexes',	'Total Stats',	'Base Stats',	'W/F',	'SM',	'A/W',	'D/W',	'IR',	'PAC',	'SHO',	'PAS',	'DRI',	'DEF',	'PHY',	'Hits']]

### Rename some columns

In [ ]:
data.rename(columns = {'‚ÜìOVA':'Overal', 'POT':'Potential', 'BOV':'Best Overall', 'BP':'Blance','IR':'Reputation'}, inplace = True)

<ipython-input-81-952cb8a99257>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.rename(columns = {'OVA':'Overal', 'POT':'Potential', 'BOV':'Best Overall', 'BP':'Blance','IR':'Reputation'}, inplace = True)

### Export to csv file

In [ ]:
data.to_csv('fifa21_clean_data.csv')